version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - pgdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/socialMedia
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=maxcrysis1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    restart: always
  pgdb:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maxcrysis1
      - POSTGRES_DB=socialMedia
    ports:
      - "5432:5432"
    restart: always
